"""referrer

Revision ID: 1fca3750410f
Revises: 5589197aa59d
Create Date: 2017-10-21 05:53:20.583429

"""

# revision identifiers, used by Alembic.
revision = '1fca3750410f'
down_revision = '5589197aa59d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('referrer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_log', 'referrer')
    # ### end Alembic commands ###
