"""remove AccessLog views

Revision ID: 3899b963ad47
Revises: 7e3220e5be0c
Create Date: 2017-10-21 03:34:51.423129

"""

# revision identifiers, used by Alembic.
revision = '3899b963ad47'
down_revision = '7e3220e5be0c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_log', 'views')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
