"""access log

Revision ID: 3e335dbfd1ac
Revises: 9696a8519b79
Create Date: 2017-04-22 16:20:08.102290

"""

# revision identifiers, used by Alembic.
revision = '3e335dbfd1ac'
down_revision = '9696a8519b79'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remote_ip', sa.String(length=15), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('module', sa.String(length=10), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('method', sa.String(length=7), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_log')
    ### end Alembic commands ###
