"""remove module field

Revision ID: 423d173b35ca
Revises: 8b2604124abc
Create Date: 2017-10-02 02:15:13.533891

"""

# revision identifiers, used by Alembic.
revision = '423d173b35ca'
down_revision = '8b2604124abc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_log', 'module')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('module', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
