"""remove AccessLog update_time field

Revision ID: 5589197aa59d
Revises: 3899b963ad47
Create Date: 2017-10-21 05:39:40.429167

"""

# revision identifiers, used by Alembic.
revision = '5589197aa59d'
down_revision = '3899b963ad47'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_log', 'update_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
