"""init

Revision ID: 7b4278574aa1
Revises: fbb05115052f
Create Date: 2016-09-04 13:23:01.525699

"""

# revision identifiers, used by Alembic.
revision = '7b4278574aa1'
down_revision = 'fbb05115052f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'users', ['user_id'], ['user_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'user_id')
    ### end Alembic commands ###
