"""CreateTimeMixin

Revision ID: 7e3220e5be0c
Revises: 423d173b35ca
Create Date: 2017-10-21 03:17:25.254490

"""

# revision identifiers, used by Alembic.
revision = '7e3220e5be0c'
down_revision = '423d173b35ca'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_log', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('access_log', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_log', 'update_time')
    op.drop_column('access_log', 'create_time')
    # ### end Alembic commands ###
