"""module

Revision ID: 8b2604124abc
Revises: caa489a6c348
Create Date: 2017-06-03 02:08:44.151939

"""

# revision identifiers, used by Alembic.
revision = '8b2604124abc'
down_revision = 'caa489a6c348'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_log', 'module',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_log', 'module',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
