"""article views

Revision ID: 9696a8519b79
Revises: 7b4278574aa1
Create Date: 2017-03-29 03:12:20.426882

"""

# revision identifiers, used by Alembic.
revision = '9696a8519b79'
down_revision = '7b4278574aa1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('views', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'views')
    ### end Alembic commands ###
